# Generated by Django 2.2b1 on 2019-04-26 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190425_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='username',
        ),
    ]
