# Generated by Django 2.2b1 on 2019-04-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodgroup',
            name='bgtype',
            field=models.CharField(choices=[('A+', 'Apositive'), ('B+', 'Bpositive'), ('AB+', 'ABpositive'), ('A-', 'Anegative'), ('B-', 'Bnegative'), ('O+', 'Opositive'), ('O-', 'Onegative')], default=1, max_length=5),
            preserve_default=False,
        ),
    ]
