# Generated by Django 2.2b1 on 2019-04-08 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_group', '0002_bloodgroup_bgtype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BloodGroup',
            new_name='Blood',
        ),
        migrations.RenameField(
            model_name='blood',
            old_name='bgtype',
            new_name='bloodgrouptype',
        ),
    ]
