# Generated by Django 2.2b1 on 2019-04-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_group', '0003_auto_20190408_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood',
            name='bloodgrouptype',
            field=models.CharField(choices=[('A+', 'A-Positive'), ('B+', 'B-Positive'), ('AB+', 'AB-Positive'), ('A-', 'A-Negative'), ('B-', 'B-Negative'), ('O+', 'O-Positive'), ('O-', 'O-Negative'), ('AB-', 'AB-Negative')], max_length=15),
        ),
    ]
