# Generated by Django 2.2b1 on 2019-04-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_group', '0004_auto_20190418_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood',
            name='city',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
