# Generated by Django 2.2b1 on 2019-04-08 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
    ]
