# Generated by Django 2.2b1 on 2019-04-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_directory_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory_info',
            name='Contact',
            field=models.IntegerField(),
        ),
    ]
