# Generated by Django 2.2b1 on 2019-04-19 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0009_auto_20190418_1329'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
