# Generated by Django 2.2b1 on 2019-04-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0010_delete_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory_info',
            name='image',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
